# Generated by Django 4.2.4 on 2024-06-13 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_of_org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_acc_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='staff_user_user_permissions', related_query_name='user_permission', to='auth.permission'),
        ),
    ]
