# Generated by Django 6.0.2 on 2026-02-13 07:04

import common.utils
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('grandfather_name', models.CharField(blank=True, max_length=150, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('identity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=50, null=True)),
                ('identity_documents_front', models.FileField(blank=True, null=True, upload_to='identity/%Y/%m/%d/front/')),
                ('identity_documents_back', models.FileField(blank=True, null=True, upload_to='identity/%Y/%m/%d/back/')),
                ('secondary_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_viber_number', models.CharField(blank=True, max_length=20, null=True)),
                ('permanent_address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address_district', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address_city_village_area', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address_ward_no', models.CharField(blank=True, max_length=10, null=True)),
                ('is_current_address_same_as_permanent', models.BooleanField(default=True)),
                ('current_address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_district', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_city_village_area', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address_ward_no', models.CharField(blank=True, max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('highest_education', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('accept', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor KYC',
                'verbose_name_plural': 'Visitor KYC',
            },
        ),
        migrations.CreateModel(
            name='VisitorsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('file', models.ImageField(blank=True, null=True, upload_to='visitors/messages', validators=[common.utils.validate_image_size])),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor Message',
                'verbose_name_plural': 'Visitor Messages',
                'ordering': ['-created'],
            },
        ),
    ]
