# Generated by Django 6.0.2 on 2026-02-13 07:04

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCMPushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.JSONField()),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'FCM Push Notification',
                'verbose_name_plural': 'FCM Push Notifications',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('notification_type', models.CharField(blank=True, choices=[('all', 'All'), ('promotional', 'Promotional'), ('wishes', 'Wishes'), ('other', 'Other')], max_length=255, null=True)),
                ('audience', models.CharField(blank=True, choices=[('staff', 'Staff'), ('visitor', 'Visitor'), ('branch', 'Branch'), ('organization', 'Organization'), ('all', 'All'), ('Individual User', 'Individual User')], max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('attach_file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('is_seen', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created'],
            },
        ),
    ]
