# Generated by Django 4.2.4 on 2024-06-13 06:15

import ckeditor.fields
import common.utils
from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='ads_banners/')),
                ('link_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_id', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('country', models.CharField(default=None, max_length=100)),
                ('state', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(default=None, max_length=100)),
                ('additional_requirements', models.TextField(blank=True, default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_device', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('android', 'Android'), ('computer', 'Computer'), ('other', 'Other')], default='other', max_length=200, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('numAdultguest', models.IntegerField(blank=True, null=True)),
                ('numChildguest', models.IntegerField(blank=True, null=True)),
                ('numofroom', models.IntegerField(blank=True, null=True)),
                ('type_of_id', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('advancedPayment', models.IntegerField(blank=True, null=True)),
                ('remainingPayment', models.IntegerField(blank=True, null=True)),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('paymentmethod', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetingappoiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('meeting_title', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('meeting_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(default='example@example.com', max_length=254, unique=True)),
                ('password', models.CharField(default=None, max_length=128)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_no', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('city_village_area', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_no', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_size', models.CharField(blank=True, max_length=200, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='branch_qr/%Y/')),
                ('lock_branch', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='OrganizationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('terms_and_conditions', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('faqs', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Org Content',
                'verbose_name_plural': 'Org Contents',
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=organization.models.upload_to_organization_document)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='OrganizationFCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('fcm_token', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('establishment_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('city_village_area', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_no', models.IntegerField(blank=True, null=True)),
                ('contact_person_full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organization_summary', models.TextField(blank=True, null=True)),
                ('whatsapp_viber_number', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_number', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
                ('registration_certificate', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
                ('PAN_VAT_certificate', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
                ('licenses', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
                ('citizenship', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
                ('driving_license', models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=200)),
            ],
            options={
                'verbose_name': 'Organization KYC',
                'verbose_name_plural': 'Organization KYC',
            },
        ),
        migrations.CreateModel(
            name='OrganizationKYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='organization_kyc/documents/%Y/%m/%d/', validators=[common.utils.validate_file_size])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationKYCSocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationSocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='OrganizationVisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
                ('purpose', models.CharField(max_length=250)),
                ('have_vehicle', models.BooleanField(blank=True, default=False, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_with_team', models.BooleanField(blank=True, default=False, null=True)),
                ('number_of_team', models.IntegerField(blank=True, default=0, null=True)),
                ('visiting_from', models.CharField(blank=True, max_length=250, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors/%Y/%m/%d/')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr/%Y/')),
                ('type_of_id', models.CharField(blank=True, choices=[('License', 'License'), ('Passport', 'Passport'), ('Citizenship', 'Citizenship'), ('Pan Card', 'Pan Card'), ('National ID Card', 'National ID Card')], max_length=200, null=True)),
                ('id_number', models.CharField(blank=True, max_length=200, null=True)),
                ('visit_type', models.CharField(choices=[('Manual', 'Manual'), ('Scan', 'Scan')], max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField()),
            ],
        ),
    ]
