# Generated by Django 6.0.2 on 2026-02-13 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerregistration',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guest',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingappointment',
            name='org_meet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingappointment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='organization_branch_groups', related_query_name='group', to='auth.group'),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='organization_branch_permissions', related_query_name='user_permission', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='organizationcontent',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationfcmtoken',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_kyc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='documents',
            field=models.ManyToManyField(blank=True, to='organization.organizationkycdocument'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='social_media_links',
            field=models.ManyToManyField(blank=True, to='organization.organizationkycsocialmedialink'),
        ),
        migrations.AddField(
            model_name='organizationsocialmedialink',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationvisithistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiting_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationvisithistory',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationbranch',
            unique_together={('organization', 'branch_no')},
        ),
        migrations.AddIndex(
            model_name='organizationvisithistory',
            index=models.Index(fields=['organization', 'is_approved'], name='organizatio_organiz_98cc43_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationvisithistory',
            index=models.Index(fields=['visited_at'], name='organizatio_visited_712a80_idx'),
        ),
    ]
