# Generated by Django 4.2.4 on 2024-06-13 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationvisithistory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visiting_organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationvisithistory',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationsocialmedialink',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='documents',
            field=models.ManyToManyField(to='organization.organizationkycdocument'),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationkyc',
            name='social_media_links',
            field=models.ManyToManyField(to='organization.organizationkycsocialmedialink'),
        ),
        migrations.AddField(
            model_name='organizationfcmtoken',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_fcm_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationcontent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='organization_branch_groups', related_query_name='group', to='auth.group'),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='organization_branch_permissions', related_query_name='user_permission', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='meetingappoiment',
            name='org_meet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_org', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingappoiment',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guest',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_org', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationbranch',
            unique_together={('organization', 'branch_no')},
        ),
    ]
